import React, { useState, useEffect } from 'react';
import WalletButton from '../components/WalletButton';
import Image from 'next/image';
import Head from 'next/head';
import Link from 'next/link';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1
          className={
            'font-bold animate-textAnimation bg-300% text-6xl bg-gradient-to-tr from-fuchsia-500 via-blue-300 to-pink-500 bg-clip-text text-transparent'
          }
        >
          Career Expo! 2022
        </h1>

        <p className={styles.description}>
          {' '}
          <code className={styles.code}>Chose Your Domain Below</code>
        </p>

        <div className={styles.grid}>
          <a href='/companyform' className={styles.card}>
            <h2>Company&rarr;</h2>
            <p>Search your next Torch bearer</p>
          </a>

          <Link href='/jobs'>
            <a className={styles.card}>
              <h2>Applicant&rarr;</h2>
              <p>Apply your dream job today</p>
            </a>
          </Link>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href='https://www.valist.io/'
          target='_blank'
          rel='noopener noreferrer'
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image
              src='/Valist-Logo.svg'
              alt='Vercel Logo'
              width={72}
              height={16}
              color={'pink'}
            />
          </span>
        </a>

        <a
          href='https://polygon.technology/'
          target='_blank'
          rel='noopener noreferrer'
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
